### ISSUE TITLE
Crypto operations do not work with Application Default Credentials

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#180] opened 2016-09-06 13:11 UTC
_From @inlined on September 5, 2016 20:4_
#### Environment details
- OS: Any (with application default credentials installed. E.g. GCE)
- Node.js version: Any
- npm version: Any
- google-cloud-node version: Head
#### Steps to reproduce
1. require `google-cloud`
2. default initialize API
3. Call getSignedUrl()

Expected: should work.
Actual: get error `Failed to obtain signed URL for file { SigningError: Could not get credentials without a JSON, pem, or p12 keyfile}"`

I took a bit of a dive into the code. `google-cloud-node` is using `google-auto-auth`, which is correctly returning the application default credential in this environment. Both `getSignedPolicy` and `getSignedUrl` call `getCredential` which only works if the developer provided a p12 or json service account file. Since Application Default Credentials are preferred where available, we should have a fallback to using `authClient.getToken()`. This can be used to call the [signBlob API](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob), which lets you do crypto with just an access token.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1565_

**Comment by stephenplusplus** [comment] 2016-09-06 13:12
Thanks for the tip, @inlined. I didn't know that endpoint existed. I moved this to the common repo shared between languages in case the other teams can benefit from this change as well.

**Comment by zbjornson** [comment] 2016-10-24 21:15
Just hit this with `getSignedUrl` -- seems like a bug, not an enhancement, though?

**Comment by stephenplusplus** [comment] 2016-10-24 23:56
RE: enhancement vs bug-- whichever :) I chose enhancement because this is adding functionality that didn't exist previously, at least in google-cloud-node. We document that the user must provide a key file in order for `getSigned___` to work.

**Comment by zbjornson** [comment] 2016-10-25 00:58
@stephenplusplus hrmmm I actually can't find that mentioned in any of the storage docs...

Re: inlined's suggestion, the signBlob API requires the `https://www.googleapis.com/auth/iam` or `https://www.googleapis.com/auth/cloud-platform` scope, whereas the rest of the storage package works with the `storage` scopes only, I think. Not sure that there's any other way, but another bit to document if this happens.

**Comment by stephenplusplus** [comment] 2016-10-25 01:44
:\ I'm almost certain we had it in our docs at one time. In any case, we "document" it in our error, so this is still a feature for us. Thanks for bringing up the scopes issue, that shouldn't be a deal breaker, as many other APIs require that scope anyway.

**Comment by dsimmons** [comment] 2016-11-11 18:19
Just ran into this myself.

Locally:
  - `gcloud beta auth application-default login`
  - Attempted to sign image assets located in GCS for short-lived access using `google-cloud-node`.

Other GCP services like PubSub work just fine using the same Application Default Credentials.

Suppose I'll be keeping my explicit service account configuration around in the interim. Definitely something I'd like to eliminate if possible, because shipping around secrets in a secure way is an added level of effort.

**Comment by stephenplusplus** [comment] 2017-03-22 19:29
@inlined / anyone:

> This can be used to call the signBlob API, which lets you do crypto with just an access token.

It looks like the path in the URI requires the email from the service account:

> The resource name of the service account in the following format: `projects/{PROJECT_ID}/serviceAccounts/{SERVICE_ACCOUNT_EMAIL}`. Using - as a wildcard for the project will infer the project from the account. The account value can be the email address or the uniqueId of the service account.

Any ideas for working around this?

**Comment by stephenplusplus** [comment] 2017-03-27 15:28
@bjwatson (feel free to tag others for more help) in GCE, it's possible to get service account information from the metadata server. It looks like it has information about service accounts associated with the VM, so we could pick one and use it as the `{SERVICE_ACCOUNT_EMAIL}` value. Does that sound correct?

In other auto-auth'd environments, such as a GAE Flex Node.js app, will that same method work / is there another?

**Comment by bjwatson** [comment] 2017-03-27 18:47
Tagging @anthmgoogle @vchudnov-g, who have more auth context than I.

**Comment by pvdyck** [comment] 2017-05-10 08:48
Same problem here, from google cloud functions, trying to get the download url ( signed url ) from a freshly generated thumbnail using https://github.com/firebase/functions-samples/tree/master/generate-thumbnail

Any update ?

**Comment by simonbengtsson** [comment] 2017-05-26 18:05
For reference, as posted [here](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1880#issuecomment-304349797), a workaround for this is to specify the keyfile manually: 

```js
const gcs = require('@google-cloud/storage')({
    projectId: 'project-id-2934',
    keyFilename: './path/to/keyfile.json'
});
```

The keyfile can be downloaded by clicking `Generate new keyfile` in project settings.

**Comment by pvdyck** [comment] 2017-05-29 09:31
Ok, thanks ! 

Any plans to put this on the roadmap ?

**Comment by inlined** [comment] 2017-06-07 17:21
@pvdyck I'm curious why you need a download URL for these images. Are you not using the Firebase SDK for Cloud Storage + Firebase Rules? These automatically handle secure end-user access w/ fine grained access control.

**Comment by pvdyck** [comment] 2017-06-07 17:35
I am using a cloud function to create a thumbnail (there is a sample for that) and I store the result in GCS. Then I update the linked image with the corresponding (long lived) access URL in firebase. It might be a design mistake indeed. I probably should store the GCS file URL in firebase and decline the original and thumbnail from it using the Firebase SDK for Cloud Storage. But this implies an overhead ? One more function call ? Does it ?

**Comment by inlined** [comment] 2017-06-07 18:11
Due to web standards, it is indeed two round trips in the browser. In mobile applications the Firebase SDK for cloud storage does a single round trip that does end-user access control -> downloading bytes. You'll also get features like auto-resume on connection failure. But this is getting off topic; if you want to chat about GCS + Firebase you can ping me on our slack.

**Comment by pvdyck** [comment] 2017-06-07 18:21
@inlined It is indeed two round trips. But I just don't understand the point in using the Firebase SDK in my specific case : I am doing a facebook-like timeline with pictures (and comments and likes, etc) do you think I should do round trips for each picture => in an infiniscroll it will delay a lot the display of the thumbnails ? Or did I miss something ?

**Comment by inlined** [comment] 2017-06-08 02:27
This is the price you're paying for revocable access. If you're merely making globally visible thumbnails then you could just as easily mark the file as publicly readable. there's a 1:1 mapping of gs:// URLs to publicly downloadable URLs.

**Comment by pvdyck** [comment] 2017-06-08 07:47
@inlined ok, so you are right, what I am searching for is to make the thumbnails publicly readable. Thanks !

**Comment by jasonpolites** [comment] 2017-08-29 21:00
@stephenplusplus I'm trying to parse this comment log to understand why this issue was closed, as it's still an issue.  The `getSignedUrl` method does not work with default application credentials on either Cloud Functions or on GCE.  The *workaround* of including the key file seems unnecessary as there's no reason that inheriting the credentials from the execution environment should be any different (from the developer's perspective).

Can we re-open this and provide a fix?

**Comment by stephenplusplus** [comment] 2017-08-29 21:23
The last investigation left me with a question I haven't heard an answer for: https://github.com/GoogleCloudPlatform/google-cloud-common/issues/180#issuecomment-289489538

I don't spend much time in GCF or GCE, so if anyone can contribute a technical solution, I can then handle the implementation in google-cloud-node.

**Comment by inlined** [comment] 2017-08-31 03:39
@stephenplusplus Sorry, you were asking for the email address of the service account? After some tinkering it seems like you can get the email address with:

```
curl -H 'Metadata-Flavor: Google' 'http://metadata/computeMetadata/v1/instance/service-accounts/default/email'
```
The server is incredibly strict; you must have the header and cannot have a trailing slash.

**Comment by stephenplusplus** [comment] 2017-08-31 13:19
Thank you! Is that endpoint available across all of GCP (GAE / GCF / GCE / GKE)? And is it safe to assume it will always return the email address of the correct service account that google-cloud-* should use?

**Comment by inlined** [comment] 2017-09-04 20:40
Honestly, I'm just basing this off of the docs and what I can easily verify exist in GCE (via the Google Cloud Shell) and in GCF (via a test app I have that lets me execute arbitrary javascript).

The key 'service-accounts' is documented [here](https://cloud.google.com/compute/docs/storing-retrieving-metadata#default) though I found the "email" endpoint through spelunking.

**Comment by jasonpolites** [comment] 2017-09-07 18:28
FWIW I can confirm that this location works from GCF and returns the expected service account.  You can also list the other resources available with:

```
curl -H 'Metadata-Flavor: Google' -vs 'http://metadata/computeMetadata/v1/instance/service-accounts/default/' 2>&1
```

Which will give you something like:

```
aliases
email
scopes
token
```

Implying
```
http://metadata/computeMetadata/v1/instance/service-accounts/default/aliases
http://metadata/computeMetadata/v1/instance/service-accounts/default/email
http://metadata/computeMetadata/v1/instance/service-accounts/default/scopes
http://metadata/computeMetadata/v1/instance/service-accounts/default/token
```

**Comment by inlined** [comment] 2017-09-26 04:53
@stephenplusplus The metadata interface is stable and should be the same across GCE, GCF, GAE, GCF, GKE. Anything you need from us to help get this closed?

**Comment by stephenplusplus** [comment] 2017-09-26 14:25
@inlined @jasonpolites Thanks for the help. I've opened an issue on the Node.js Storage repo (https://github.com/googleapis/nodejs-storage/issues/39)-- I'm not sure where the other languages stand on their support for this.

**Comment by Crazometer** [comment] 2018-05-01 05:53
Can this be fixed now that the linked issue is sorted?

**Comment by inlined** [comment] 2018-05-01 14:41
I've been following/driving this fix for about two years now =/

Last I recall, the issue you linked makes everything technically feasible given the right IAM permissions, but the default permissions for many deployments won't have the signIAM permission necessary. The last requirement is that through edge casing or the metadata service a service running as service account X always has/defaults to having permission to call projects/yourProject/serviceAccounts/X:signBlob and :signJWT

**Comment by chadananda** [comment] 2019-12-19 02:00
Is there another way to get a downloadURL for stored files? I really don't care about revoking access. I can easily upload and get a URL from the client -- but the only way to do it from a Cloud Function is to push the file over to S3. There must be something I am missing!

**Comment by busunkim96** [comment] 2019-12-19 23:51
@chadananda Are you using NodeJS or some other language?

**Closed** 2020-08-07 01:58 UTC
Labels: storage
