### ISSUE TITLE
No anchor links to pin to subheadings?

### ISSUE THREAD

**Issue by stephenplusplus** [googleapis/google-cloud-common#40] opened 2015-11-30 17:07 UTC
_From @jgeewax on September 29, 2015 15:50_

I wanted to send a reference to the "With gcloud-node" section on http://googlecloudplatform.github.io/gcloud-node/#/authentication but it looks like there's no paragraph anchor link...

Any chance we can add one of those?

_Copied from original issue: GoogleCloudPlatform/gcloud-node#899_

**Comment by stephenplusplus** [comment] 2015-11-30 17:07
_From @callmehiphop on September 30, 2015 5:57_

It doesn't look like any of the markdown content has anchor tags.. was it always like this? Regardless, I'm not sure if showdown offers this as an option so we may have to write an extension.

**Comment by stephenplusplus** [comment] 2015-11-30 17:07
_From @jgeewax on September 30, 2015 14:42_

I'm not sure if we ever had this working -- I suspect not... however maybe h2 and higher should have anchors? Or all headings?

Not the most important thing, but definitely something in the "nice to have" category.

**Comment by quartzmo** [comment] 2016-09-23 16:45
The title of this issue should be generalized to address all headings, or else should be closed as a duplicate of later issue #137.

**Closed** 2018-10-01 17:14 UTC
Labels: docs
