### ISSUE TITLE
Explore switching to another CI provider?

### ISSUE THREAD

**Issue by jgeewax** [googleapis/google-cloud-common#32] opened 2015-10-04 16:26 UTC
Travis is awesome, but has a couple of issues:
1. If we depend on gRPC (which eventually most of us will), we won't be able to run our tests using it (the install requires an apt package to be installed, which I don't think Travis will do).
2. If we want more parallelism, the highest level of granularity we have is at the organization level. This means that we can't just buy more parallelism for gcloud-\* builds -- we can only buy for the whole GCP organization (which includes lots of stuff). I spoke with Travis support about this, and they say they can't really help us with that...

(I brought this up before just with the second point, and we decided things were "good enough", which is fine, but now we have the gRPC issue, and didn't want to leave the parallel builds issue out of the discussion.)

Anyone have experience with CircleCI? I'd really rather not host our own Jenkins machines, but if it comes to that we can certainly do so.

**Comment by blowmage** [comment] 2015-10-04 16:50
We can [install packages with apt](http://docs.travis-ci.com/user/customizing-the-build/#Installing-Packages-Using-apt) on Travis-ci. 

I know folks who use Circle-ci, but don't have any experience myself.

**Comment by jgeewax** [comment] 2015-10-04 16:54
> We can install packages with apt on Travis-ci.

OK, let me add in more scary complicated stuff: technically it's not apt-installable right now... it's "sort of kind of maybe if you really want it" apt installable (add something to sources.list, etc). Once we get it actually working (ie, `apt-get install grpc`) then we're in much better shape. No idea when that will be.

What about adding PPAs ?

**Comment by blowmage** [comment] 2015-10-04 17:00
I think I've added PPAs to a Travis build before. AFAIK it should works fine. I'll play around with it this week.

**Comment by jgeewax** [comment] 2015-10-04 17:02
Got it -- still not an option for us today (gRPC just ... isn't there yet) so we need to be able to run arbitrary commands as of now. Eventually though a PPA should cover us.

**Comment by stephenplusplus** [comment] 2015-10-04 19:13
After seeing some unfortunate lack-of-attention to important issues from the Travis team + unwilling to work with us (weird?), I'm willing to throw my vote towards whatever *will* work for us. No experience with the competition, but to throw another name out there: https://codeship.com

**Comment by devth** [comment] 2016-05-25 14:41
FWIW: my experience with GitLab CI + Pipelines is pretty great. You guys should check it out :) 

I was up and running from zero to multi-stage pipeline in < 1 hr.

https://about.gitlab.com/2016/05/22/gitlab-8-8-released/

**Comment by blowmage** [comment] 2016-09-13 14:46
For the past several weeks we've seen a large slowdown in build times starting around noon to early evening. Basically, we can't rely on any change made after lunch to complete before the end of the work day. Its been awful.

I like Travis-CI. I have no problems with it. But I'm very open to moving to other CI providers if it means we can get back to timely builds.

**Comment by daspecster** [comment] 2016-09-13 15:12
@blowmage, I've seen the same thing as well.

It was faster for a few days here and there but it seems to now be the norm.

We track it here somewhat.
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2200

**Comment by quartzmo** [comment] 2016-09-13 15:48
Given that @jgeewax has already investigated the possibility of increasing capacity with Travis, I am also very motivated to solve the problem by moving to a different CI provider.

**Comment by tseaver** [comment] 2016-09-13 16:44
AFAIK, Google could throw money at the problem, but would need to scale it across all the activity in this `GoogleCloudPlatform` organization (no per-repository charges).  It could be argued that guaranteeing us less latency would actually *save* Google money.
![travis](https://cloud.githubusercontent.com/assets/242750/18482821/b46612e4-79af-11e6-8e76-66c41a088e49.png)

**Comment by blowmage** [comment] 2016-09-13 16:45
Something something separate organizations per language... :trollface:

**Comment by daspecster** [comment] 2016-09-13 17:04
I'm not sure we have any great guarantee that another service provider won't have speed or other issues.

I'm not sure what the lift would be roll something in say Kubernetes...
https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes?

**Comment by jonparrott** [comment] 2016-09-13 17:13
/cc @elibixby @waprin @broady 

The DPE team feels your pain. We're exploring some alternative solutions ourselves, so we might as well work together.

Here's where we are:

1. Travis is largely unusable for us right now.
2. We have a Jenkins instance that's currently firewalls, but @waprin is working on opening it up a little. This could allow you to do both linux and windows builds.
3. We're exploring Circle CI, because it's far easier for us to pay them money for more resources. Our attempts to do so with Travis have been unfruitful.

**Comment by jonparrott** [comment] 2016-09-13 17:13
(oops didn't mean to close)

**Comment by jba** [comment] 2016-09-13 18:51
@adams-sarah is looking into Jenkins-on-GCE for the Go repo.

**Comment by broady** [comment] 2016-09-13 20:25
What's going on with the google-cloud-node build? It looks like it takes about four hours, has no parallelization, and hasn't passed for weeks. Maybe disabling that project will alleviate some resources?

**Comment by dhermes** [comment] 2016-09-13 20:30
RE: "hasn't passed for weeks"

You'd assume the same sort of issue with [`google-cloud-python` builds][1]. However, the majority (like 99.9%) of our failures on merges to master come from flaky system tests (talking to 9 Google services in two different Python environments almost always guarantees a failure-mole will pop up that we need to hit, surprising lack of robustness in talking to Google services).

As for the 4 hours thing, I have no idea what the issue is there, though [individual jobs][2] don't seem to be the culprit.

[1]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-python/builds
[2]: https://travis-ci.org/GoogleCloudPlatform/google-cloud-node/builds/158806636

**Comment by broady** [comment] 2016-09-13 20:34
Flaky tests are still failed tests.

**Comment by stephenplusplus** [comment] 2016-09-13 20:47
Yep, we (Node) have to run in serial to avoid getting random system test failures. With Travis, we test 3 different Node versions on 2 operating systems. We support 13 services and have around 400 tests running against the API.

Regarding it taking 4 hours, we're trying to speed that up, too. A lot of the time is spent installing our dependencies from npm. We've tried some things (forcing npm 3 to dedupe dependencies before downloading) and are still trying others (only running test suites on modules that were affected by the latest change). There's also just the general lack of speed of a test that needs to create a VM, make it stop, restart, delete, etc.

Sorry to anyone affected by our slow builds. If you need to disable us, go for it. We've been relying on our own boxes for these last couple weeks anyway.

**Comment by daspecster** [comment] 2016-09-13 20:52
@stephenplusplus are you using container based builds? That would speed up the VM building.

**Comment by broady** [comment] 2016-09-13 20:53
I found Travis caches to greatly speed up fetching dependencies (for Go, that happens via git, so storing a cache is very useful).

For npm, I think it would help a lot, too.

**Comment by stephenplusplus** [comment] 2016-09-13 20:54
RE: container builds, we do. When I was talking about the VMs, I meant our own tests that need to test the lifecycle of a Compute Engine VM.

**Comment by broady** [comment] 2016-09-13 20:55
Ahhh, right. Yes, I agree - running slower tests like that only once per day or when the relevant module is changed seems like an easy win.

**Closed** 2020-08-07 01:57 UTC
